/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package features;
import com.raven.datechooser.DateBetween;
import com.raven.datechooser.DateChooser;
import com.raven.datechooser.listener.DateChooserAction;
import com.raven.datechooser.listener.DateChooserAdapter;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.ModelPengguna;
import model.ModelPromo;
import service.ServicePengaturan;
import service.ServicePromo;


/**
 *
 * @author usER
 */
public class FiturPengaturan extends javax.swing.JPanel {

    /**
     * Creates new form FiturBarang
     */
    private DateChooser dateChooser;
    private ServicePengaturan servicePengaturan = new ServicePengaturan();
    private ServicePromo servicePromo = new ServicePromo();
    private ModelPengguna modelPengguna;
    public FiturPengaturan(String slide, ModelPengguna modelPengguna) {
        initComponents();
        this.modelPengguna = modelPengguna;
        dataAkun();
        dateChooser = new DateChooser();
        lbNotif.setVisible(false);
        style();
        changePanel(slide);
        rentang();
    }
    
    private void style() {
        cbxJenisPromo.setFont(new Font("sansserif",0,20));
        cbxJenisPromo.setBackground(new Color(255,255,255));
        cbxJenisPromo.setForeground(new Color(0,0,0));
    }
    
    private void changePanel(String slide) {
        switch(slide) {
            case "Slide-Akun" :
                removeAll();
                add(panelAkun);
                repaint();
                revalidate();
                break;
            case "Slide-Password" :
                removeAll();
                add(panelPassword);
                repaint();
                revalidate();
                break;
            case "Slide-Promo" :
                removeAll();
                add(panelPromo);
                repaint();
                revalidate();
                break;
        }
    }
    
    private void clearField() {
        txtNama.setText(null);
        txtUsername.setText(null);
        txtEmail.setText(null);
    }
    
    public void backAcount(ActionListener action) {
        btnBack1.addActionListener(action);
    }
    
    private void back(JPanel panel) {
        removeAll();
        add(panel);
        repaint();
        revalidate();
    }
    
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAkun = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        lb_nama = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnSimpan1 = new swing.Button();
        jPanel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        btnBack1 = new swing.Button();
        panelPassword = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();
        lb_old = new javax.swing.JLabel();
        lb_new = new javax.swing.JLabel();
        lb_confirm = new javax.swing.JLabel();
        txtConfirPass = new javax.swing.JTextField();
        txtOldPass = new javax.swing.JTextField();
        txtNewPass = new javax.swing.JTextField();
        btnSimpan2 = new swing.Button();
        jPanel2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        btnBack2 = new swing.Button();
        panelPromo = new javax.swing.JPanel();
        panel4 = new javax.swing.JPanel();
        lb_harga = new javax.swing.JLabel();
        lb_rentang = new javax.swing.JLabel();
        txtPromo = new javax.swing.JTextField();
        txtRentang = new javax.swing.JTextField();
        btnSimpan3 = new swing.Button();
        lb_jenis = new javax.swing.JLabel();
        cbxJenisPromo = new javax.swing.JComboBox<>();
        btnViewPromo = new swing.Button();
        lb_tglAwal = new javax.swing.JLabel();
        lb_tglAkhir = new javax.swing.JLabel();
        lbNotif = new javax.swing.JLabel();
        txtNamaPromo = new javax.swing.JTextField();
        lb_rentang1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        btnBack3 = new swing.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelAkun.setBackground(new java.awt.Color(153, 153, 153));
        panelAkun.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        panel2.setBackground(new java.awt.Color(255, 255, 255));

        lb_nama.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_nama.setForeground(new java.awt.Color(0, 0, 0));
        lb_nama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_nama.setText("Nama");

        lb_email.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_email.setForeground(new java.awt.Color(0, 0, 0));
        lb_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_email.setText("Email");

        lb_username.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_username.setForeground(new java.awt.Color(0, 0, 0));
        lb_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_username.setText("Username");

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        txtNama.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        txtUsername.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        btnSimpan1.setBackground(new java.awt.Color(135, 15, 50));
        btnSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan1.setText("PERBARUI");
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nama)
                            .addComponent(lb_email))
                        .addGap(43, 43, 43)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(txtUsername)
                            .addComponent(txtNama))))
                .addGap(26, 26, 26))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(135, 15, 50));

        label1.setBackground(new java.awt.Color(135, 15, 50));
        label1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("AKUN");

        btnBack1.setBackground(new java.awt.Color(135, 15, 50));
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right-arrow.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAkunLayout = new javax.swing.GroupLayout(panelAkun);
        panelAkun.setLayout(panelAkunLayout);
        panelAkunLayout.setHorizontalGroup(
            panelAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAkunLayout.createSequentialGroup()
                        .addGap(0, 114, Short.MAX_VALUE)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAkunLayout.setVerticalGroup(
            panelAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        add(panelAkun, "card2");

        panelPassword.setBackground(new java.awt.Color(153, 153, 153));
        panelPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        panel3.setBackground(new java.awt.Color(255, 255, 255));

        lb_old.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_old.setForeground(new java.awt.Color(0, 0, 0));
        lb_old.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_old.setText("Password Lama");

        lb_new.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_new.setForeground(new java.awt.Color(0, 0, 0));
        lb_new.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_new.setText("Konfirmasi Password");

        lb_confirm.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_confirm.setForeground(new java.awt.Color(0, 0, 0));
        lb_confirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_confirm.setText("Password Baru");

        txtConfirPass.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtConfirPass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        txtOldPass.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtOldPass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        txtNewPass.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtNewPass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        btnSimpan2.setBackground(new java.awt.Color(135, 15, 50));
        btnSimpan2.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan2.setText("SIMPAN");
        btnSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_old, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_new)
                            .addComponent(lb_confirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConfirPass, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(txtNewPass)
                            .addComponent(txtOldPass))))
                .addGap(26, 26, 26))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_old, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_new, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(135, 15, 50));

        label2.setBackground(new java.awt.Color(135, 15, 50));
        label2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Ubah Password");

        btnBack2.setBackground(new java.awt.Color(135, 15, 50));
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right-arrow.png"))); // NOI18N
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasswordLayout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        add(panelPassword, "card3");

        panelPromo.setBackground(new java.awt.Color(153, 153, 153));
        panelPromo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        panel4.setBackground(new java.awt.Color(255, 255, 255));

        lb_harga.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_harga.setForeground(new java.awt.Color(0, 0, 0));
        lb_harga.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_harga.setText("Potongan");

        lb_rentang.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_rentang.setForeground(new java.awt.Color(0, 0, 0));
        lb_rentang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_rentang.setText("Rentang");

        txtPromo.setFont(new java.awt.Font("SansSerif", 2, 20)); // NOI18N
        txtPromo.setForeground(new java.awt.Color(185, 185, 185));
        txtPromo.setText("Contoh (10000)");
        txtPromo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));
        txtPromo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPromoFocusGained(evt);
            }
        });
        txtPromo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPromoKeyTyped(evt);
            }
        });

        txtRentang.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtRentang.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        btnSimpan3.setBackground(new java.awt.Color(135, 15, 50));
        btnSimpan3.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan3.setText("SIMPAN");
        btnSimpan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan3ActionPerformed(evt);
            }
        });

        lb_jenis.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_jenis.setForeground(new java.awt.Color(0, 0, 0));
        lb_jenis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_jenis.setText("Jenis Promo");

        cbxJenisPromo.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        cbxJenisPromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Potongan harga langsung", "Diskon % dari harga jual" }));
        cbxJenisPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJenisPromoActionPerformed(evt);
            }
        });

        btnViewPromo.setBackground(new java.awt.Color(0, 153, 0));
        btnViewPromo.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPromo.setText("Lihat Daftar Promo");
        btnViewPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPromoActionPerformed(evt);
            }
        });

        lb_tglAwal.setForeground(new java.awt.Color(255, 255, 255));
        lb_tglAwal.setText("tglAwal");

        lb_tglAkhir.setForeground(new java.awt.Color(255, 255, 255));
        lb_tglAkhir.setText("tglAkhir");

        lbNotif.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbNotif.setForeground(new java.awt.Color(135, 15, 50));
        lbNotif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNotif.setText("Masukkan Hanya Angka");

        txtNamaPromo.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtNamaPromo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        lb_rentang1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lb_rentang1.setForeground(new java.awt.Color(0, 0, 0));
        lb_rentang1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_rentang1.setText("Nama Promo");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_tglAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_rentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_jenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_tglAkhir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_rentang1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnViewPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPromo)
                            .addComponent(txtRentang)
                            .addComponent(cbxJenisPromo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamaPromo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(26, 26, 26))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_rentang1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rentang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRentang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxJenisPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(lb_tglAwal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_tglAkhir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(135, 15, 50));

        label3.setBackground(new java.awt.Color(135, 15, 50));
        label3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Atur Promo");

        btnBack3.setBackground(new java.awt.Color(135, 15, 50));
        btnBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right-arrow.png"))); // NOI18N
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(label3)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPromoLayout = new javax.swing.GroupLayout(panelPromo);
        panelPromo.setLayout(panelPromoLayout);
        panelPromoLayout.setHorizontalGroup(
            panelPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPromoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPromoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPromoLayout.setVerticalGroup(
            panelPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPromoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        add(panelPromo, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        aturAkun();
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan2ActionPerformed
        ubahPassword();
    }//GEN-LAST:event_btnSimpan2ActionPerformed

    private void btnSimpan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan3ActionPerformed
        Date date = new Date();
        String dateNow = new SimpleDateFormat("yyyy-MM-dd").format(date);
        String strDate = txtRentang.getText();
        if(!strDate.equals(dateNow)) {
        aturPromo();    
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan Tentukan Rentang Promo");
        }
    }//GEN-LAST:event_btnSimpan3ActionPerformed

    private void btnViewPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPromoActionPerformed
        LihatPromo promo = new LihatPromo(null, true);
        promo.setVisible(true);
    }//GEN-LAST:event_btnViewPromoActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        back(new Dashboard(modelPengguna));
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void cbxJenisPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJenisPromoActionPerformed
        int index = cbxJenisPromo.getSelectedIndex();
        switch(index) {
            case 0: 
                lb_harga.setText("Potongan");
                txtPromo.setForeground(new Color(185, 185, 185));
                txtPromo.setFont(new Font("sansserif", Font.ITALIC, 20));
                txtPromo.setText("Contoh (10000)");
                break;
            case 1:
                lb_harga.setText("Diskon %");
                txtPromo.setForeground(new Color(185, 185, 185));
                txtPromo.setFont(new Font("sansserif", Font.ITALIC, 20));
                txtPromo.setText("Contoh (5), Maks 100%");
                break;
        }
    }//GEN-LAST:event_cbxJenisPromoActionPerformed

    private void txtPromoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPromoFocusGained
        txtPromo.setText(null);
        txtPromo.setForeground(new Color(0, 0, 0));
        txtPromo.setFont(new Font("sansserif", Font.PLAIN, 20));       
    }//GEN-LAST:event_txtPromoFocusGained

    private void txtPromoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPromoKeyTyped
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)) {
            lbNotif.setVisible(false);
        } else {
           evt.consume();
           lbNotif.setVisible(true);
        }
    }//GEN-LAST:event_txtPromoKeyTyped

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        back(new Dashboard(modelPengguna));
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        back(new Dashboard(modelPengguna));
    }//GEN-LAST:event_btnBack2ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnBack1;
    private swing.Button btnBack2;
    private swing.Button btnBack3;
    private swing.Button btnSimpan1;
    private swing.Button btnSimpan2;
    private swing.Button btnSimpan3;
    private swing.Button btnViewPromo;
    private javax.swing.JComboBox<String> cbxJenisPromo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel lbNotif;
    private javax.swing.JLabel lb_confirm;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_harga;
    private javax.swing.JLabel lb_jenis;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_new;
    private javax.swing.JLabel lb_old;
    private javax.swing.JLabel lb_rentang;
    private javax.swing.JLabel lb_rentang1;
    private javax.swing.JLabel lb_tglAkhir;
    private javax.swing.JLabel lb_tglAwal;
    private javax.swing.JLabel lb_username;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panelAkun;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelPromo;
    private javax.swing.JTextField txtConfirPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaPromo;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtOldPass;
    private javax.swing.JTextField txtPromo;
    private javax.swing.JTextField txtRentang;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

//  Akun
    private void dataAkun() {
        List<String> listData = servicePengaturan.loadAccount(modelPengguna);
        for(int a = 0; a < listData.size(); a++) {
        txtNama.setText(listData.get(0));
        txtUsername.setText(listData.get(1));
        txtEmail.setText(listData.get(2));   
        }
    }
    
    private void aturAkun() {
        ModelPengguna modelPengguna = new ModelPengguna();
        modelPengguna.setIdpengguna(this.modelPengguna.getIdpengguna());
        modelPengguna.setNama(txtNama.getText());
        modelPengguna.setUsername(txtUsername.getText());
        modelPengguna.setEmail(txtEmail.getText());
        servicePengaturan.setAccount(modelPengguna);
    }
    
//    Ubah Password
    private void ubahPassword() {
        ModelPengguna modelPengguna = new ModelPengguna();
        String idPengguna = this.modelPengguna.getIdpengguna();
        String oldPassword = txtOldPass.getText();
        String newPassword = txtNewPass.getText();
        String confirPass = txtConfirPass.getText();
        modelPengguna.setIdpengguna(idPengguna);
        modelPengguna.setPassword(newPassword);
                
        if(oldPassword.equals(this.modelPengguna.getPassword())) {
            if(confirPass.equals(newPassword)) {
            servicePengaturan.setPassword(modelPengguna);
            } else {
            JOptionPane.showMessageDialog(null, "Konfirmasi password salah");   
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password lama salah");
        } 
    }

//    Atur Promo
    private void aturPromo() {
        String noPromosi = servicePromo.createNo();
        String namaPromo = txtNamaPromo.getText();
        String tglAwal = lb_tglAwal.getText();
        String tglAkhir = lb_tglAkhir.getText();
        String jenis = null;
        String keterangan;
        
        LocalDate thisDate = LocalDate.now();
        LocalDate startDate = LocalDate.parse(tglAwal);
        int hariIni = thisDate.getDayOfMonth();
        int bulanIni = thisDate.getMonthValue();
        int tahunIni = thisDate.getYear();
        int mulaiHariPromo = startDate.getDayOfMonth();
        int mulaiBulanPromo = startDate.getMonthValue();
        int mulaiTahunPromo = startDate.getYear();
        
        if(mulaiTahunPromo > tahunIni || mulaiBulanPromo > bulanIni || mulaiHariPromo > hariIni) {
            keterangan = "Akan Datang";
        } else {
            keterangan = "Berjalan";
        }
        
        int index = cbxJenisPromo.getSelectedIndex();
        switch(index) {
            case 0: 
                jenis = "Langsung";
                break;
            case 1:
                jenis = "Persentase";
                break;
        }
        int banyak = Integer.parseInt(txtPromo.getText());
        ModelPromo promo = new ModelPromo(noPromosi, namaPromo, tglAwal, tglAkhir, banyak, jenis, keterangan);
        if(validation(promo)) {
            servicePromo.addPromo(promo);   
            txtNamaPromo.setText(null);
            txtPromo.setText(null);
        } else {
            JOptionPane.showMessageDialog(null, "Terdapat Promo yang Sedang Berjalan");
        }
    }
    
    
    private void rentang() {
        dateChooser = new DateChooser();
        dateChooser.setBetweenCharacter(" Sampai ");
        dateChooser.setTextField(txtRentang);
        dateChooser.setDateSelectionMode(DateChooser.DateSelectionMode.BETWEEN_DATE_SELECTED);
        dateChooser.setLabelCurrentDayVisible(false);
        dateChooser.setDateFormat(new SimpleDateFormat("yyyy-MM-dd"));
        dateChooser.setSelectedDate(new Date());
        dateChooser.addActionDateChooserListener(new DateChooserAdapter() {
            @Override
            public void dateBetweenChanged(DateBetween date, DateChooserAction action) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fromDate = sdf.format(date.getFromDate());
                String toDate = sdf.format(date.getToDate());
                lb_tglAwal.setText(fromDate);
                lb_tglAkhir.setText(toDate);
            }
        });
    }
    
    private boolean validation(ModelPromo modelPromo) {
        boolean valid = false;
        String keterangan = servicePromo.getKeterangan(modelPromo);
        if(keterangan.equals("Akan Datang")) {
            valid = true;
        }
        return valid;
    }

}
