/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import action.ActionMenu;
import action.ActionMenuSelected;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.ModelMenu;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author usER
 */
public class MenuItem extends javax.swing.JPanel {

    /**
     * Creates new form MenuItem
     */
    private float alpha;
    private ModelMenu menu;
    private boolean open;
    private ActionMenuSelected actionSelected;
    private int index;

    public float getAlpha() {
        return alpha;
    }

    public void setAlpha(float alpha) {
        this.alpha = alpha;
    }

    public ModelMenu getMenu() {
        return menu;
    }

    public void setMenu(ModelMenu menu) {
        this.menu = menu;
    }

    public boolean isOpen() {
        return open;
    }

    public void setOpen(boolean open) {
        this.open = open;
    }

    public ActionMenuSelected getActionSelected() {
        return actionSelected;
    }

    public void setActionSelected(ActionMenuSelected actionSelected) {
        this.actionSelected = actionSelected;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }
    public MenuItem(ModelMenu menu, ActionMenu action, ActionMenuSelected actionSelected, int index) {
        initComponents();
        this.menu = menu;
        this.actionSelected = actionSelected;
        this.index = index;
        setOpaque(false);
        setLayout(new MigLayout("wrap, fillx, insets 0","[fill]","[fill, 40!]0[fill, 35!]"));
        MenuButton firstItem = new MenuButton(menu.getIcon(), " "+menu.getMenuName());
        firstItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(menu.getSubMenu().length > 0) {
                   if(action.menuPressed(MenuItem.this, !open)) {
                       open = !open;
                   }
                }
                
                actionSelected.menuSelected(index, -1);
            }
        });
        
        add(firstItem);
        
        int subMenuIndex = -1;
        for(String item : menu.getSubMenu()) {
            MenuButton items = new MenuButton(item);
            items.setIndex(++subMenuIndex);
            items.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    actionSelected.menuSelected(index, items.getIndex());
                }
            });
            
            add(items);
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        int width = getWidth();
        int heigth = getPreferredSize().height;
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(135, 15, 50));
        g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, alpha));
        g2.fillRect(0, 2, width, 38);
        g2.setComposite(AlphaComposite.SrcOver);
        g2.fillRect(0, 40, width, heigth - 40);
        g2.setColor(new Color(135, 15, 50));
        
        if(menu.getSubMenu().length > 0) {
            int size = 4;
            int y = 19;
            int x = 205;
            g2.setColor(new Color(255, 255, 255));
            float y1 = alpha * size;
            float y2 = (1f - alpha) * size;
            g2.drawLine(x, (int)(y + y1), x + 4, (int)(y + y2));
            g2.drawLine(x + 4, (int)(y + y2), x + 8, (int)(y + y1));
        }
        
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
