/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import features.Pengaturan;
import java.awt.Point;
import java.awt.event.ActionListener;
import model.ModelPengguna;

/**
 *
 * @author usER
 */
public class Navbar extends javax.swing.JPanel {

    /**
     * Creates new form Navbar
     */
    public Pengaturan settings;
    public Navbar(ModelPengguna modelPengguna) {
        initComponents();
        settings = new Pengaturan(null, true, modelPengguna);
        lbName.setText(modelPengguna.getNama());
        lbId1.setText(modelPengguna.getIdpengguna());
        lbId.setText(modelPengguna.getLevel());
    }
    
    public void addAction(ActionListener action) {
        btn.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNotif = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        lbId1 = new javax.swing.JLabel();
        btn = new swing.Button();
        setting = new swing.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        lbNotif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bell.png"))); // NOI18N
        lbNotif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNotif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNotifMouseClicked(evt);
            }
        });

        lbName.setBackground(new java.awt.Color(255, 255, 255));
        lbName.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(135, 15, 50));
        lbName.setText("Ali Akbar Rafsanjani");

        lbId.setBackground(new java.awt.Color(255, 255, 255));
        lbId.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lbId.setForeground(new java.awt.Color(135, 15, 50));
        lbId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbId.setText("Admin");

        lbId1.setBackground(new java.awt.Color(255, 255, 255));
        lbId1.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lbId1.setForeground(new java.awt.Color(135, 15, 50));
        lbId1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbId1.setText("USR-001");

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/burger-bar-2.png"))); // NOI18N

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/setting.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbName)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbId1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(setting, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(lbId1)))
            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        Point point = setting.getLocationOnScreen();
        int x = point.x + setting.getWidth() - settings.getWidth();
        int y = point.y + setting.getHeight();
        settings.setLocation(x, y);
        settings.setVisible(true);
    }//GEN-LAST:event_settingActionPerformed

    private void lbNotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNotifMouseClicked
        System.out.println("Click");
    }//GEN-LAST:event_lbNotifMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbId1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNotif;
    private swing.Button setting;
    // End of variables declaration//GEN-END:variables
}
